[tool.poetry]
name = "spartan-framework"
version = "0.1.8"
description = "A micro framework for serverless development in AWS"
authors = ["Sydel Palinlin <sydel.palinlin@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = "^3.11"
httpx = "^0.25.0"
python-dotenv = "^1.0.0"
email-validator = "^2.0.0.post2"
jsonpickle = "^3.0.2"
python-jose = "^3.3.0"
pymysql = "^1.1.0"
pydantic-settings = "^2.5.2"
pydantic = "^2.9.2"
sqlalchemy = "^2.0.35"
aws-lambda-powertools = "^3.1.0"
boto3 = "^1.35.49"
pg8000 = "^1.31.2"
fastapi = "^0.115.4"


[tool.poetry.group.dev.dependencies]
autoflake = "^2.2.1"
boto3 = "^1.28.66"
alembic = "^1.13.3"
pytest = "^8.3.3"
pytest-cov = "^5.0.0"
black = "^23.9.1"
isort = "^5.12.0"
flake8 = "^6.1.0"
bandit = "^1.7.5"
poetry-plugin-export = "^1.8.0"
pytest-mock = "^3.12.0"
pytest-asyncio = "^0.21.1"
faker = "^30.8.2"
moto = "4.2.9"


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=."
testpaths = [
    "tests",
    "integrations",
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
